# Change these first
owner: hkfires # Your GitHub organization or username, where this repository lives
repo: WebMonitor # The name of this repository

sites:
  - name: Serv00-1
    url: $URL_SERV00_1
  - name: Serv00-2
    url: $URL_SERV00_2
  - name: Serv00-3
    url: $URL_SERV00_3
  - name: Bot-Serv00
    url: $URL_BOT_SERV00
  - name: Bot-CT8
    url: $URL_BOT_CT8
  - name: Google
    url: https://www.google.com
  - name: Baidu
    url: https://www.baidu.com/
  - name: Cloudflare
    url: https://www.cloudflare.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: light
  baseUrl: /WebMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WebMonitor
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
